### ISSUE TITLE
failed to parse 20.erb

### ISSUE THREAD

**Issue by grbailey66** [thias/puppet-fooacl#8]
New to puppet so this could be simple -- I missed something obvious...

Downloaded fooacl as tar ball, untarred and renamed fooacl in my modulepath.

touched /tmp/foobar for test file on puppet agent system

used puppet module generate to create module named try
init.pp:
    class try {
       include fooacl
       fooacl::conf { "/tmp/foobar":
            permissions => [
                                      'user::splunk:r--',
                                    ],
     }
}

included try in test node in site.pp

Got the following error:  ??

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template fooacl/20.erb:
  Filepath: /etc/puppetlabs/puppet/environments/dsade/modules/fooacl/templates/20.erb
  Line: 1
  Detail: undefined method `each' for "/tmp/foobar":String
 at /etc/puppetlabs/puppet/environments/dsade/modules/fooacl/manifests/conf.pp:16 on node ess0840x.dre.dev.int
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by thias** [comment]
No reply in a loooong time. Assuming this was indeed fixed :-)

**Comment by grbailey66** [comment]
yes, your original suggestion worked for me.

Glenn
